"""
Gold standard test data generator.

Generates 20 medically accurate synthetic test cases covering:
- 5 FHIR bundle cases
- 10 plain text cases
- 5 image cases (text content, images generated by generate_test_images.py)

Each case includes expected entities, ICD-10 codes, negation annotations,
CDI gap hints, and KG qualification rules.
"""

import json
from pathlib import Path
from datetime import datetime

# Define all 20 gold standard cases
GOLD_STANDARD_CASES = [
    # === FHIR Bundle Cases (1-3, 20) ===
    {
        "case_id": "case_001",
        "source_type": "fhir",
        "input_data": "cliniq/data/gold_standard/fhir_bundles/case_001.json",
        "notes": "Type 2 diabetes with neuropathy and retinopathy complications",
        "expected_entities": [
            {"text": "Type 2 diabetes mellitus", "entity_type": "diagnosis", "start_char": 0, "end_char": 25, "negated": False, "qualifiers": ["type 2"]},
            {"text": "diabetic neuropathy", "entity_type": "diagnosis", "start_char": 31, "end_char": 50, "negated": False, "qualifiers": []},
            {"text": "diabetic retinopathy", "entity_type": "diagnosis", "start_char": 56, "end_char": 76, "negated": False, "qualifiers": []}
        ],
        "expected_icd10_codes": ["E11.40", "E11.311"],
        "expected_principal_dx": "E11.40",
        "expected_comorbidities": ["E11.311"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "no evidence of diabetic ketoacidosis", "entity": "diabetic ketoacidosis", "negated": True},
            {"text": "patient has diabetic retinopathy", "entity": "diabetic retinopathy", "negated": False}
        ],
        "cdi_gap_annotations": [
            {"code": "E11.40", "missing_qualifier": "severity of neuropathy", "query_hint": "What is the severity of the diabetic neuropathy?"}
        ],
        "kg_qualification_rules": [
            {"code": "E11.40", "requires": ["complication_type", "laterality"]},
            {"code": "E11.311", "requires": ["laterality", "severity"]}
        ],
        "fhir_bundle": {
            "resourceType": "Bundle",
            "type": "collection",
            "entry": [
                {
                    "resource": {
                        "resourceType": "Patient",
                        "id": "patient-001",
                        "name": [{"family": "Johnson", "given": ["Robert"]}],
                        "gender": "male",
                        "birthDate": "1965-03-12"
                    }
                },
                {
                    "resource": {
                        "resourceType": "Encounter",
                        "id": "encounter-001",
                        "status": "finished",
                        "class": {"system": "http://terminology.hl7.org/CodeSystem/v3-ActCode", "code": "IMP", "display": "inpatient encounter"},
                        "subject": {"reference": "Patient/patient-001"},
                        "period": {"start": "2026-03-15T09:00:00Z", "end": "2026-03-18T14:00:00Z"}
                    }
                },
                {
                    "resource": {
                        "resourceType": "Condition",
                        "id": "condition-001-1",
                        "subject": {"reference": "Patient/patient-001"},
                        "code": {
                            "coding": [{"system": "http://hl7.org/fhir/sid/icd-10-cm", "code": "E11.40", "display": "Type 2 diabetes mellitus with diabetic neuropathy"}],
                            "text": "Type 2 diabetes mellitus with neuropathy"
                        },
                        "clinicalStatus": {"coding": [{"system": "http://terminology.hl7.org/CodeSystem/condition-clinical", "code": "active"}]}
                    }
                },
                {
                    "resource": {
                        "resourceType": "Condition",
                        "id": "condition-001-2",
                        "subject": {"reference": "Patient/patient-001"},
                        "code": {
                            "coding": [{"system": "http://hl7.org/fhir/sid/icd-10-cm", "code": "E11.311", "display": "Type 2 diabetes mellitus with unspecified diabetic retinopathy with macular edema"}],
                            "text": "Type 2 diabetes mellitus with diabetic retinopathy"
                        },
                        "clinicalStatus": {"coding": [{"system": "http://terminology.hl7.org/CodeSystem/condition-clinical", "code": "active"}]}
                    }
                }
            ]
        }
    },
    {
        "case_id": "case_002",
        "source_type": "fhir",
        "input_data": "cliniq/data/gold_standard/fhir_bundles/case_002.json",
        "notes": "Acute myocardial infarction with heart failure",
        "expected_entities": [
            {"text": "acute myocardial infarction", "entity_type": "diagnosis", "start_char": 0, "end_char": 27, "negated": False, "qualifiers": ["acute"]},
            {"text": "congestive heart failure", "entity_type": "diagnosis", "start_char": 33, "end_char": 57, "negated": False, "qualifiers": []},
            {"text": "elevated troponin", "entity_type": "lab_finding", "start_char": 62, "end_char": 79, "negated": False, "qualifiers": ["elevated"]}
        ],
        "expected_icd10_codes": ["I21.9", "I50.9"],
        "expected_principal_dx": "I21.9",
        "expected_comorbidities": ["I50.9"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "no signs of arrhythmia", "entity": "arrhythmia", "negated": True},
            {"text": "patient presents with chest pain", "entity": "chest pain", "negated": False}
        ],
        "cdi_gap_annotations": [
            {"code": "I21.9", "missing_qualifier": "specific arterial location", "query_hint": "Which coronary artery was affected?"}
        ],
        "kg_qualification_rules": [
            {"code": "I21.9", "requires": ["arterial_location", "STEMI_vs_NSTEMI"]},
            {"code": "I50.9", "requires": ["acuity", "systolic_diastolic"]}
        ],
        "fhir_bundle": {
            "resourceType": "Bundle",
            "type": "collection",
            "entry": [
                {
                    "resource": {
                        "resourceType": "Patient",
                        "id": "patient-002",
                        "name": [{"family": "Martinez", "given": ["Maria"]}],
                        "gender": "female",
                        "birthDate": "1958-07-22"
                    }
                },
                {
                    "resource": {
                        "resourceType": "Encounter",
                        "id": "encounter-002",
                        "status": "finished",
                        "class": {"system": "http://terminology.hl7.org/CodeSystem/v3-ActCode", "code": "EMER", "display": "emergency"},
                        "subject": {"reference": "Patient/patient-002"},
                        "period": {"start": "2026-03-16T14:30:00Z", "end": "2026-03-16T20:00:00Z"}
                    }
                },
                {
                    "resource": {
                        "resourceType": "Condition",
                        "id": "condition-002-1",
                        "subject": {"reference": "Patient/patient-002"},
                        "code": {
                            "coding": [{"system": "http://hl7.org/fhir/sid/icd-10-cm", "code": "I21.9", "display": "Acute myocardial infarction, unspecified"}],
                            "text": "Acute myocardial infarction"
                        },
                        "clinicalStatus": {"coding": [{"system": "http://terminology.hl7.org/CodeSystem/condition-clinical", "code": "active"}]}
                    }
                },
                {
                    "resource": {
                        "resourceType": "Condition",
                        "id": "condition-002-2",
                        "subject": {"reference": "Patient/patient-002"},
                        "code": {
                            "coding": [{"system": "http://hl7.org/fhir/sid/icd-10-cm", "code": "I50.9", "display": "Heart failure, unspecified"}],
                            "text": "Congestive heart failure"
                        },
                        "clinicalStatus": {"coding": [{"system": "http://terminology.hl7.org/CodeSystem/condition-clinical", "code": "active"}]}
                    }
                }
            ]
        }
    },
    {
        "case_id": "case_003",
        "source_type": "fhir",
        "input_data": "cliniq/data/gold_standard/fhir_bundles/case_003.json",
        "notes": "COPD exacerbation with pneumonia",
        "expected_entities": [
            {"text": "COPD exacerbation", "entity_type": "diagnosis", "start_char": 0, "end_char": 17, "negated": False, "qualifiers": ["exacerbation"]},
            {"text": "pneumonia", "entity_type": "diagnosis", "start_char": 23, "end_char": 32, "negated": False, "qualifiers": []},
            {"text": "oxygen supplementation", "entity_type": "treatment", "start_char": 37, "end_char": 59, "negated": False, "qualifiers": ["supplemental"]}
        ],
        "expected_icd10_codes": ["J44.1", "J18.9"],
        "expected_principal_dx": "J44.1",
        "expected_comorbidities": ["J18.9"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "denies fever", "entity": "fever", "negated": True},
            {"text": "reports dyspnea", "entity": "dyspnea", "negated": False}
        ],
        "cdi_gap_annotations": [
            {"code": "J44.1", "missing_qualifier": "with or without lower respiratory infection", "query_hint": "Is there concurrent lower respiratory infection?"}
        ],
        "kg_qualification_rules": [
            {"code": "J44.1", "requires": ["acute_chronic", "with_lower_respiratory_infection"]},
            {"code": "J18.9", "requires": ["organism", "laterality"]}
        ],
        "fhir_bundle": {
            "resourceType": "Bundle",
            "type": "collection",
            "entry": [
                {
                    "resource": {
                        "resourceType": "Patient",
                        "id": "patient-003",
                        "name": [{"family": "Chen", "given": ["Wei"]}],
                        "gender": "male",
                        "birthDate": "1952-11-08"
                    }
                },
                {
                    "resource": {
                        "resourceType": "Encounter",
                        "id": "encounter-003",
                        "status": "finished",
                        "class": {"system": "http://terminology.hl7.org/CodeSystem/v3-ActCode", "code": "IMP", "display": "inpatient encounter"},
                        "subject": {"reference": "Patient/patient-003"},
                        "period": {"start": "2026-03-14T08:00:00Z", "end": "2026-03-17T16:00:00Z"}
                    }
                },
                {
                    "resource": {
                        "resourceType": "Condition",
                        "id": "condition-003-1",
                        "subject": {"reference": "Patient/patient-003"},
                        "code": {
                            "coding": [{"system": "http://hl7.org/fhir/sid/icd-10-cm", "code": "J44.1", "display": "Chronic obstructive pulmonary disease with (acute) exacerbation"}],
                            "text": "COPD exacerbation"
                        },
                        "clinicalStatus": {"coding": [{"system": "http://terminology.hl7.org/CodeSystem/condition-clinical", "code": "active"}]}
                    }
                },
                {
                    "resource": {
                        "resourceType": "Condition",
                        "id": "condition-003-2",
                        "subject": {"reference": "Patient/patient-003"},
                        "code": {
                            "coding": [{"system": "http://hl7.org/fhir/sid/icd-10-cm", "code": "J18.9", "display": "Pneumonia, unspecified organism"}],
                            "text": "Pneumonia"
                        },
                        "clinicalStatus": {"coding": [{"system": "http://terminology.hl7.org/CodeSystem/condition-clinical", "code": "active"}]}
                    }
                }
            ]
        }
    },
    {
        "case_id": "case_020",
        "source_type": "fhir",
        "input_data": "cliniq/data/gold_standard/fhir_bundles/case_020.json",
        "notes": "Orthopedic follow-up with multiple procedures",
        "expected_entities": [
            {"text": "total hip replacement", "entity_type": "procedure", "start_char": 0, "end_char": 21, "negated": False, "qualifiers": ["total"]},
            {"text": "physical therapy", "entity_type": "procedure", "start_char": 27, "end_char": 43, "negated": False, "qualifiers": []},
            {"text": "osteoarthritis", "entity_type": "diagnosis", "start_char": 48, "end_char": 62, "negated": False, "qualifiers": ["hip"]}
        ],
        "expected_icd10_codes": ["Z96.641", "Z47.1"],
        "expected_principal_dx": "Z96.641",
        "expected_comorbidities": ["Z47.1"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "no signs of infection", "entity": "infection", "negated": True},
            {"text": "patient reports pain", "entity": "pain", "negated": False}
        ],
        "cdi_gap_annotations": [
            {"code": "Z96.641", "missing_qualifier": "laterality", "query_hint": "Which hip (left or right)?"}
        ],
        "kg_qualification_rules": [
            {"code": "Z96.641", "requires": ["laterality"]},
            {"code": "Z47.1", "requires": ["procedure_type"]}
        ],
        "fhir_bundle": {
            "resourceType": "Bundle",
            "type": "collection",
            "entry": [
                {
                    "resource": {
                        "resourceType": "Patient",
                        "id": "patient-020",
                        "name": [{"family": "Thompson", "given": ["James"]}],
                        "gender": "male",
                        "birthDate": "1948-06-30"
                    }
                },
                {
                    "resource": {
                        "resourceType": "Encounter",
                        "id": "encounter-020",
                        "status": "finished",
                        "class": {"system": "http://terminology.hl7.org/CodeSystem/v3-ActCode", "code": "AMB", "display": "ambulatory"},
                        "subject": {"reference": "Patient/patient-020"},
                        "period": {"start": "2026-03-18T10:00:00Z", "end": "2026-03-18T11:00:00Z"}
                    }
                },
                {
                    "resource": {
                        "resourceType": "Condition",
                        "id": "condition-020-1",
                        "subject": {"reference": "Patient/patient-020"},
                        "code": {
                            "coding": [{"system": "http://hl7.org/fhir/sid/icd-10-cm", "code": "Z96.641", "display": "Presence of right artificial hip joint"}],
                            "text": "Status post total hip replacement"
                        },
                        "clinicalStatus": {"coding": [{"system": "http://terminology.hl7.org/CodeSystem/condition-clinical", "code": "active"}]}
                    }
                },
                {
                    "resource": {
                        "resourceType": "Procedure",
                        "id": "procedure-020-1",
                        "status": "completed",
                        "code": {
                            "coding": [{"system": "http://hl7.org/fhir/sid/icd-10-cm", "code": "Z47.1", "display": "Aftercare following joint replacement surgery"}],
                            "text": "Physical therapy aftercare"
                        },
                        "subject": {"reference": "Patient/patient-020"}
                    }
                }
            ]
        }
    },
]

# Text note cases (4-14)
TEXT_NOTES = {
    "case_004": """Chief Complaint: Follow-up for chronic kidney disease and hypertension.

History of Present Illness: Patient is a 68-year-old male with stage 3 chronic kidney disease (eGFR 45 mL/min/1.73m²) and hypertension. He reports good blood pressure control on current medications (lisinopril 20mg daily, amlodipine 5mg daily). Denies chest pain, denies shortness of breath. No edema noted. Patient reports compliance with low-sodium diet and medication regimen.

Assessment and Plan:
1. Chronic kidney disease, stage 3 (N18.3) - stable, continue current management
2. Essential hypertension (I10) - well controlled, continue medications
3. Follow up in 3 months with repeat labs (BMP, eGFR)""",

    "case_005": """Chief Complaint: Depression and anxiety management.

History of Present Illness: 45-year-old female with major depressive disorder and generalized anxiety disorder. Patient reports persistent low mood, difficulty sleeping, and excessive worry for the past 6 months. No suicidal ideation. Denies manic episodes. She denies substance abuse. Currently on sertraline 100mg daily with partial response.

Mental Status Exam: Alert and oriented x3. Depressed affect. No psychotic features. Insight and judgment intact.

Assessment and Plan:
1. Major depressive disorder, recurrent episode, moderate (F33.1)
2. Generalized anxiety disorder (F41.1)
3. Increase sertraline to 150mg daily
4. Recommend cognitive behavioral therapy
5. Follow up in 4 weeks""",

    "case_006": """Chief Complaint: Post-surgical wound infection.

History of Present Illness: 72-year-old female status post right total hip replacement 3 weeks ago. Presents with wound erythema, purulent drainage, and fever (101.2°F). Surgical site shows signs of infection with surrounding cellulitis. Denies chest pain. No respiratory symptoms. Patient reports increased pain at surgical site.

Physical Exam: Vital signs: Temp 101.2°F, BP 135/82, HR 92, RR 16. Surgical wound: 3cm area of erythema, purulent drainage noted, warmth and tenderness present.

Assessment and Plan:
1. Post-procedural wound infection (T81.4XXA) following hip replacement
2. Cellulitis of right hip region (L03.115)
3. Obtain wound culture
4. Start IV vancomycin 1g q12h
5. Consult orthopedic surgery
6. Admission for IV antibiotics""",

    "case_007": """Chief Complaint: Asthma exacerbation.

History of Present Illness: 28-year-old male with history of moderate persistent asthma presents with acute exacerbation. Patient reports 3 days of progressive dyspnea, wheezing, and cough. Currently using albuterol inhaler every 2-3 hours without relief. Denies fever. No sick contacts. Triggered by recent upper respiratory infection. Patient denies chest pain.

Physical Exam: Respiratory: bilateral expiratory wheezing, increased work of breathing. Peak flow 60% of personal best.

Assessment and Plan:
1. Asthma with acute exacerbation (J45.41)
2. Nebulized albuterol with ipratropium
3. Oral prednisone 60mg daily x 5 days
4. Continue maintenance inhaled corticosteroid
5. Follow up in 1 week""",

    "case_008": """Chief Complaint: Breast cancer follow-up.

History of Present Illness: 58-year-old female with recently diagnosed infiltrating ductal carcinoma of the left breast. Pathology shows ER-positive, PR-positive, HER2-negative invasive carcinoma with lymph node involvement (2 of 15 nodes positive). Tumor size 2.5cm. Patient completed lumpectomy 2 weeks ago. No signs of surgical site infection. Denies fever, denies wound drainage.

Assessment and Plan:
1. Malignant neoplasm of upper-outer quadrant of left breast with lymph node involvement (C50.412, C77.3)
2. Referral to medical oncology for adjuvant chemotherapy discussion
3. Referral to radiation oncology for radiation therapy planning
4. Start aromatase inhibitor after chemotherapy completion
5. Genetic counseling referral""",

    "case_009": """Chief Complaint: Urinary tract infection.

History of Present Illness: 62-year-old female with type 2 diabetes mellitus presents with dysuria, urinary frequency, and suprapubic pain for 2 days. Patient reports cloudy urine with foul odor. Denies fever. Denies flank pain. No nausea or vomiting. Blood sugar readings have been elevated (180-220 mg/dL) over past 2 days. Patient denies vaginal discharge.

Urinalysis: Positive leukocyte esterase, 50+ WBCs, nitrite positive, bacteria present.

Assessment and Plan:
1. Urinary tract infection, site not specified (N39.0)
2. Type 2 diabetes mellitus without complications (E11.9) - currently uncontrolled
3. Ciprofloxacin 500mg PO BID x 7 days
4. Increase metformin from 1000mg to 1500mg BID
5. Repeat urinalysis after treatment
6. Follow up in 2 weeks""",

    "case_010": """Chief Complaint: Heart failure and atrial fibrillation management.

History of Present Illness: 75-year-old male with congestive heart failure (LVEF 30%) and chronic atrial fibrillation presents for routine follow-up. Patient reports mild dyspnea on exertion, controlled with current diuretic regimen. No orthopnea. Denies chest pain. Weight stable. Patient compliant with furosemide 40mg daily and carvedilol 25mg BID. On apixaban for anticoagulation.

Physical Exam: Cardiovascular: irregular rhythm, no murmurs. Lungs: clear to auscultation. Extremities: trace bilateral lower extremity edema.

Assessment and Plan:
1. Congestive heart failure, chronic systolic (I50.22) - compensated
2. Chronic atrial fibrillation (I48.20) - rate controlled
3. Continue current medications
4. Low sodium diet counseling
5. Daily weights monitoring
6. Follow up in 3 months""",

    "case_011": """Chief Complaint: Chronic pain management for osteoarthritis.

History of Present Illness: 69-year-old female with bilateral knee osteoarthritis and chronic lower back pain. Patient reports daily pain rated 6/10, worse with activity. She denies radiculopathy. Currently taking acetaminophen 1000mg TID with minimal relief. Patient denies fall risk. Physical therapy completed 6 months ago with limited benefit. No previous joint replacements.

Physical Exam: Musculoskeletal: bilateral knee crepitus, limited range of motion. Lumbar spine: tenderness to palpation L4-S1.

Assessment and Plan:
1. Bilateral primary osteoarthritis of knee (M17.0)
2. Chronic low back pain (M54.5)
3. Start meloxicam 15mg daily
4. Referral to orthopedics for possible knee replacement evaluation
5. Consider spinal imaging if pain worsens
6. Follow up in 6 weeks""",

    "case_012": """Chief Complaint: Stroke follow-up with residual deficits.

History of Present Illness: 71-year-old male status post ischemic stroke 6 months ago affecting left middle cerebral artery territory. Patient has residual right-sided hemiplegia and expressive aphasia. Currently receiving outpatient physical therapy and speech therapy. Patient denies recent falls. On aspirin and atorvastatin for stroke prevention. Caregiver reports gradual improvement in functional status.

Physical Exam: Neurological: right upper extremity 2/5 strength, right lower extremity 3/5 strength. Expressive aphasia present. Alert and follows commands.

Assessment and Plan:
1. Late effects of cerebrovascular disease with hemiplegia affecting right dominant side (I69.351)
2. Late effects of cerebrovascular disease with aphasia (I69.320)
3. Continue stroke prevention medications
4. Continue physical therapy and speech therapy
5. Caregiver support resources provided
6. Follow up in 2 months""",

    "case_013": """Chief Complaint: Pneumonia with sepsis.

History of Present Illness: 80-year-old female from nursing home presents with fever (102.8°F), productive cough, and altered mental status for 2 days. Patient has history of dementia and hypertension. No recent travel. Chest x-ray shows right lower lobe infiltrate consistent with bacterial pneumonia. Lactate elevated at 3.2 mmol/L. Blood pressure 85/50 mmHg. Patient denies chest pain when lucid.

Physical Exam: Vital signs: Temp 102.8°F, BP 85/50, HR 110, RR 28, O2 sat 88% on room air. Respiratory: decreased breath sounds right base, crackles. Mental status: confused, disoriented to time and place.

Assessment and Plan:
1. Severe bacterial pneumonia, right lower lobe (J15.9)
2. Sepsis due to pneumonia (A41.9)
3. Admission to ICU
4. Start broad-spectrum antibiotics (ceftriaxone + azithromycin)
5. IV fluid resuscitation
6. Continuous monitoring""",

    "case_014": """Chief Complaint: Hypothyroidism with fatigue.

History of Present Illness: 52-year-old female with primary hypothyroidism presents with persistent fatigue, weight gain (15 lbs over 6 months), and cold intolerance. Patient reports compliance with levothyroxine 75mcg daily. Denies depression. No hair loss or skin changes. TSH recently checked: 8.5 mIU/L (elevated).

Physical Exam: Vital signs: BP 128/78, HR 62. General: appears fatigued but non-toxic. Thyroid: not palpably enlarged.

Assessment and Plan:
1. Hypothyroidism, primary (E03.9) - currently under-treated
2. Increase levothyroxine to 100mcg daily
3. Repeat TSH in 6 weeks
4. Nutrition counseling for weight management
5. Follow up after lab results available""",
}

# Text case metadata (4-14)
TEXT_CASE_METADATA = [
    {
        "case_id": "case_004",
        "expected_entities": [
            {"text": "chronic kidney disease", "entity_type": "diagnosis", "start_char": 23, "end_char": 45, "negated": False, "qualifiers": ["chronic", "stage 3"]},
            {"text": "hypertension", "entity_type": "diagnosis", "start_char": 50, "end_char": 62, "negated": False, "qualifiers": ["essential"]},
            {"text": "chest pain", "entity_type": "diagnosis", "start_char": 280, "end_char": 290, "negated": True, "qualifiers": []},
            {"text": "shortness of breath", "entity_type": "diagnosis", "start_char": 299, "end_char": 318, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["N18.3", "I10"],
        "expected_principal_dx": "N18.3",
        "expected_comorbidities": ["I10"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "Denies chest pain", "entity": "chest pain", "negated": True},
            {"text": "denies shortness of breath", "entity": "shortness of breath", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "N18.3", "missing_qualifier": "specific eGFR value", "query_hint": "What is the patient's current eGFR?"}
        ],
        "kg_qualification_rules": [
            {"code": "N18.3", "requires": ["eGFR_range", "stage"]},
            {"code": "I10", "requires": ["controlled_uncontrolled"]}
        ]
    },
    {
        "case_id": "case_005",
        "expected_entities": [
            {"text": "major depressive disorder", "entity_type": "diagnosis", "start_char": 78, "end_char": 103, "negated": False, "qualifiers": ["major", "recurrent"]},
            {"text": "generalized anxiety disorder", "entity_type": "diagnosis", "start_char": 108, "end_char": 136, "negated": False, "qualifiers": ["generalized"]},
            {"text": "suicidal ideation", "entity_type": "diagnosis", "start_char": 230, "end_char": 247, "negated": True, "qualifiers": []},
            {"text": "substance abuse", "entity_type": "diagnosis", "start_char": 270, "end_char": 285, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["F33.1", "F41.1"],
        "expected_principal_dx": "F33.1",
        "expected_comorbidities": ["F41.1"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "No suicidal ideation", "entity": "suicidal ideation", "negated": True},
            {"text": "Denies manic episodes", "entity": "manic episodes", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "F33.1", "missing_qualifier": "with or without psychotic features", "query_hint": "Are psychotic features present?"}
        ],
        "kg_qualification_rules": [
            {"code": "F33.1", "requires": ["severity", "psychotic_features"]},
            {"code": "F41.1", "requires": ["severity"]}
        ]
    },
    {
        "case_id": "case_006",
        "expected_entities": [
            {"text": "wound infection", "entity_type": "diagnosis", "start_char": 20, "end_char": 35, "negated": False, "qualifiers": ["post-surgical"]},
            {"text": "cellulitis", "entity_type": "diagnosis", "start_char": 220, "end_char": 230, "negated": False, "qualifiers": []},
            {"text": "hip replacement", "entity_type": "procedure", "start_char": 75, "end_char": 90, "negated": False, "qualifiers": ["total", "right"]},
            {"text": "chest pain", "entity_type": "diagnosis", "start_char": 245, "end_char": 255, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["T81.4XXA", "L03.115"],
        "expected_principal_dx": "T81.4XXA",
        "expected_comorbidities": [],
        "expected_complications": ["L03.115"],
        "negation_test_cases": [
            {"text": "Denies chest pain", "entity": "chest pain", "negated": True},
            {"text": "No respiratory symptoms", "entity": "respiratory symptoms", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "T81.4XXA", "missing_qualifier": "organism", "query_hint": "What organism was cultured from the wound?"}
        ],
        "kg_qualification_rules": [
            {"code": "T81.4XXA", "requires": ["encounter_context", "organism"]},
            {"code": "L03.115", "requires": ["laterality", "body_site"]}
        ]
    },
    {
        "case_id": "case_007",
        "expected_entities": [
            {"text": "asthma", "entity_type": "diagnosis", "start_char": 45, "end_char": 51, "negated": False, "qualifiers": ["moderate persistent"]},
            {"text": "exacerbation", "entity_type": "diagnosis", "start_char": 73, "end_char": 85, "negated": False, "qualifiers": ["acute"]},
            {"text": "dyspnea", "entity_type": "diagnosis", "start_char": 135, "end_char": 142, "negated": False, "qualifiers": ["progressive"]},
            {"text": "fever", "entity_type": "diagnosis", "start_char": 245, "end_char": 250, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["J45.41"],
        "expected_principal_dx": "J45.41",
        "expected_comorbidities": [],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "Denies fever", "entity": "fever", "negated": True},
            {"text": "Patient denies chest pain", "entity": "chest pain", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "J45.41", "missing_qualifier": "severity classification", "query_hint": "Is this mild, moderate, or severe persistent asthma?"}
        ],
        "kg_qualification_rules": [
            {"code": "J45.41", "requires": ["severity", "exacerbation_status"]}
        ]
    },
    {
        "case_id": "case_008",
        "expected_entities": [
            {"text": "breast cancer", "entity_type": "diagnosis", "start_char": 20, "end_char": 33, "negated": False, "qualifiers": ["infiltrating ductal"]},
            {"text": "invasive carcinoma", "entity_type": "diagnosis", "start_char": 145, "end_char": 163, "negated": False, "qualifiers": ["invasive"]},
            {"text": "lymph node involvement", "entity_type": "diagnosis", "start_char": 169, "end_char": 191, "negated": False, "qualifiers": []},
            {"text": "infection", "entity_type": "diagnosis", "start_char": 310, "end_char": 319, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["C50.412", "C77.3"],
        "expected_principal_dx": "C50.412",
        "expected_comorbidities": ["C77.3"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "No signs of surgical site infection", "entity": "infection", "negated": True},
            {"text": "Denies fever", "entity": "fever", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "C50.412", "missing_qualifier": "histologic grade", "query_hint": "What is the histologic grade of the tumor?"}
        ],
        "kg_qualification_rules": [
            {"code": "C50.412", "requires": ["laterality", "quadrant", "histology", "grade"]},
            {"code": "C77.3", "requires": ["number_of_nodes_involved"]}
        ]
    },
    {
        "case_id": "case_009",
        "expected_entities": [
            {"text": "urinary tract infection", "entity_type": "diagnosis", "start_char": 20, "end_char": 43, "negated": False, "qualifiers": []},
            {"text": "type 2 diabetes mellitus", "entity_type": "diagnosis", "start_char": 64, "end_char": 88, "negated": False, "qualifiers": ["type 2"]},
            {"text": "fever", "entity_type": "diagnosis", "start_char": 210, "end_char": 215, "negated": True, "qualifiers": []},
            {"text": "flank pain", "entity_type": "diagnosis", "start_char": 224, "end_char": 234, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["N39.0", "E11.9"],
        "expected_principal_dx": "N39.0",
        "expected_comorbidities": ["E11.9"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "Denies fever", "entity": "fever", "negated": True},
            {"text": "Denies flank pain", "entity": "flank pain", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "N39.0", "missing_qualifier": "organism", "query_hint": "What organism was identified in urine culture?"}
        ],
        "kg_qualification_rules": [
            {"code": "N39.0", "requires": ["organism", "site"]},
            {"code": "E11.9", "requires": ["complication", "control_status"]}
        ]
    },
    {
        "case_id": "case_010",
        "expected_entities": [
            {"text": "congestive heart failure", "entity_type": "diagnosis", "start_char": 75, "end_char": 99, "negated": False, "qualifiers": ["chronic systolic"]},
            {"text": "atrial fibrillation", "entity_type": "diagnosis", "start_char": 122, "end_char": 141, "negated": False, "qualifiers": ["chronic"]},
            {"text": "orthopnea", "entity_type": "diagnosis", "start_char": 250, "end_char": 259, "negated": True, "qualifiers": []},
            {"text": "chest pain", "entity_type": "diagnosis", "start_char": 268, "end_char": 278, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["I50.22", "I48.20"],
        "expected_principal_dx": "I50.22",
        "expected_comorbidities": ["I48.20"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "No orthopnea", "entity": "orthopnea", "negated": True},
            {"text": "Denies chest pain", "entity": "chest pain", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "I50.22", "missing_qualifier": "NYHA class", "query_hint": "What is the NYHA functional class?"}
        ],
        "kg_qualification_rules": [
            {"code": "I50.22", "requires": ["acuity", "systolic_diastolic", "NYHA_class"]},
            {"code": "I48.20", "requires": ["paroxysmal_persistent_permanent"]}
        ]
    },
    {
        "case_id": "case_011",
        "expected_entities": [
            {"text": "osteoarthritis", "entity_type": "diagnosis", "start_char": 43, "end_char": 57, "negated": False, "qualifiers": ["bilateral knee"]},
            {"text": "chronic lower back pain", "entity_type": "diagnosis", "start_char": 62, "end_char": 85, "negated": False, "qualifiers": ["chronic"]},
            {"text": "radiculopathy", "entity_type": "diagnosis", "start_char": 145, "end_char": 158, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["M17.0", "M54.5"],
        "expected_principal_dx": "M17.0",
        "expected_comorbidities": ["M54.5"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "denies radiculopathy", "entity": "radiculopathy", "negated": True},
            {"text": "Patient denies fall risk", "entity": "fall risk", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "M17.0", "missing_qualifier": "primary vs secondary", "query_hint": "Is this primary or secondary osteoarthritis?"}
        ],
        "kg_qualification_rules": [
            {"code": "M17.0", "requires": ["laterality", "primary_secondary"]},
            {"code": "M54.5", "requires": ["acuity"]}
        ]
    },
    {
        "case_id": "case_012",
        "expected_entities": [
            {"text": "ischemic stroke", "entity_type": "diagnosis", "start_char": 40, "end_char": 55, "negated": False, "qualifiers": []},
            {"text": "hemiplegia", "entity_type": "diagnosis", "start_char": 145, "end_char": 155, "negated": False, "qualifiers": ["right-sided"]},
            {"text": "aphasia", "entity_type": "diagnosis", "start_char": 170, "end_char": 177, "negated": False, "qualifiers": ["expressive"]},
            {"text": "falls", "entity_type": "diagnosis", "start_char": 265, "end_char": 270, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["I69.351", "I69.320"],
        "expected_principal_dx": "I69.351",
        "expected_comorbidities": ["I69.320"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "Patient denies recent falls", "entity": "falls", "negated": True},
            {"text": "no new ischemic events on imaging", "entity": "ischemic events", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "I69.351", "missing_qualifier": "dominant vs non-dominant side", "query_hint": "Is the right side dominant or non-dominant?"}
        ],
        "kg_qualification_rules": [
            {"code": "I69.351", "requires": ["laterality", "dominance"]},
            {"code": "I69.320", "requires": ["type_of_aphasia"]}
        ]
    },
    {
        "case_id": "case_013",
        "expected_entities": [
            {"text": "pneumonia", "entity_type": "diagnosis", "start_char": 20, "end_char": 29, "negated": False, "qualifiers": ["bacterial", "right lower lobe"]},
            {"text": "sepsis", "entity_type": "diagnosis", "start_char": 35, "end_char": 41, "negated": False, "qualifiers": []},
            {"text": "chest pain", "entity_type": "diagnosis", "start_char": 360, "end_char": 370, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["J15.9", "A41.9"],
        "expected_principal_dx": "J15.9",
        "expected_comorbidities": [],
        "expected_complications": ["A41.9"],
        "negation_test_cases": [
            {"text": "Patient denies chest pain when lucid", "entity": "chest pain", "negated": True},
            {"text": "patient is febrile with productive cough", "entity": "productive cough", "negated": False}
        ],
        "cdi_gap_annotations": [
            {"code": "J15.9", "missing_qualifier": "organism", "query_hint": "What organism was identified in sputum culture?"},
            {"code": "A41.9", "missing_qualifier": "severe sepsis criteria", "query_hint": "Does patient meet severe sepsis criteria?"}
        ],
        "kg_qualification_rules": [
            {"code": "J15.9", "requires": ["organism", "laterality", "lobe"]},
            {"code": "A41.9", "requires": ["severe_sepsis", "septic_shock", "organism"]}
        ]
    },
    {
        "case_id": "case_014",
        "expected_entities": [
            {"text": "hypothyroidism", "entity_type": "diagnosis", "start_char": 40, "end_char": 54, "negated": False, "qualifiers": ["primary"]},
            {"text": "fatigue", "entity_type": "diagnosis", "start_char": 60, "end_char": 67, "negated": False, "qualifiers": ["persistent"]},
            {"text": "depression", "entity_type": "diagnosis", "start_char": 230, "end_char": 240, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["E03.9"],
        "expected_principal_dx": "E03.9",
        "expected_comorbidities": [],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "Denies depression", "entity": "depression", "negated": True},
            {"text": "no goiter on examination", "entity": "goiter", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "E03.9", "missing_qualifier": "congenital vs acquired", "query_hint": "Is this congenital or acquired hypothyroidism?"}
        ],
        "kg_qualification_rules": [
            {"code": "E03.9", "requires": ["primary_secondary", "congenital_acquired"]}
        ]
    },
]

# Image case text (15-19) - to be rendered as images by generate_test_images.py
IMAGE_NOTES = {
    "case_015": """ORTHOPEDIC CONSULTATION NOTE

Patient: Sarah Williams
DOB: 03/15/1975
Date: 03/18/2026

CHIEF COMPLAINT: Lower back pain with right leg radiculopathy

HISTORY OF PRESENT ILLNESS:
Patient is a 51-year-old female presenting with chronic lower back pain radiating to right lower extremity. Pain began 8 months ago, progressively worsening. Reports numbness and tingling in right L5 distribution. Pain rated 7/10, worse with sitting and forward flexion. Denies bowel or bladder incontinence. No history of trauma.

PHYSICAL EXAM:
Neurological: Right L5 weakness (4/5 strength), diminished sensation L5 dermatome. Positive straight leg raise at 45 degrees on right.
Musculoskeletal: Paraspinal muscle spasm L4-S1.

IMAGING: MRI lumbar spine shows L4-L5 disc herniation with right lateral recess stenosis.

ASSESSMENT:
1. Lumbar disc herniation at L4-L5 with radiculopathy (M51.16)
2. Chronic low back pain (M54.5)
3. Right lower limb radiculopathy (M54.30)

PLAN:
1. Conservative management trial with physical therapy
2. Consider epidural steroid injection if no improvement
3. Surgical consultation if symptoms persist beyond 6 weeks
4. Pain management referral""",

    "case_016": """WOUND CARE CLINIC NOTE

Patient: Michael Rodriguez
DOB: 09/22/1968
Date: 03/18/2026

CHIEF COMPLAINT: Diabetic foot ulcer assessment

HISTORY:
58-year-old male with type 2 diabetes mellitus (20-year history), peripheral neuropathy, and peripheral vascular disease presents for follow-up of right plantar foot ulcer. Ulcer present for 6 weeks, not healing despite standard wound care. Denies fever or chills. No purulent drainage noted today.

EXAM:
Right foot: 3cm x 2cm ulcer on plantar surface of right first metatarsal head. Probes to bone. Surrounding erythema 1cm. No purulent drainage currently. Decreased sensation bilateral feet. Pedal pulses: DP 1+/4, PT 1+/4 bilaterally.

VASCULAR ASSESSMENT: ABI 0.65 right lower extremity (abnormal).

ASSESSMENT:
1. Diabetic foot ulcer, right foot (E11.621)
2. Type 2 diabetes with diabetic peripheral angiopathy (E11.51)
3. Type 2 diabetes with diabetic neuropathy (E11.40)
4. Peripheral vascular disease (I73.9)

PLAN:
1. Wound culture obtained - results pending
2. Start oral antibiotics (cephalexin 500mg QID)
3. Advanced wound dressing application
4. Strict non-weight bearing right foot
5. Vascular surgery consultation for revascularization evaluation
6. Follow-up in 1 week""",

    "case_017": """PULMONOLOGY CONSULTATION

Patient: Patricia Anderson
DOB: 06/10/1954
Date: 03/18/2026

REASON FOR CONSULTATION: Respiratory assessment and COPD management

HISTORY OF PRESENT ILLNESS:
72-year-old female with 40 pack-year smoking history (quit 5 years ago) and known COPD on home oxygen 2L continuous presents with progressive dyspnea and productive cough for 5 days. Patient reports increased sputum production (yellow-green). Using rescue inhaler more frequently. Denies hemoptysis. No fever documented.

PHYSICAL EXAMINATION:
Vital Signs: O2 sat 89% on room air, 94% on 2L NC. RR 24. HR 95. BP 138/82.
Respiratory: Prolonged expiratory phase, bilateral expiratory wheezing, decreased breath sounds at bases, no crackles.

CHEST X-RAY: Hyperinflation, flattened diaphragms, no acute infiltrate.

PULMONARY FUNCTION TESTS (from 3 months ago): FEV1 45% predicted, FEV1/FVC ratio 0.55.

ASSESSMENT:
1. Chronic obstructive pulmonary disease with acute exacerbation (J44.1)
2. Long-term current use of supplemental oxygen (Z99.81)
3. History of tobacco use (Z87.891)

PLAN:
1. Oral prednisone 40mg daily x 5 days
2. Azithromycin 500mg daily x 5 days
3. Continue home oxygen
4. Increase tiotropium to daily
5. Pulmonary rehabilitation referral
6. Smoking cessation counseling reinforcement
7. Follow-up in 2 weeks""",

    "case_018": """CARDIOLOGY CONSULTATION

Patient: David Lee
DOB: 12/05/1961
Date: 03/18/2026

CHIEF COMPLAINT: Atypical chest pain evaluation

HISTORY:
65-year-old male with hypertension, hyperlipidemia, and family history of coronary artery disease (father MI at age 58) presents with intermittent chest discomfort for 3 weeks. Patient describes pressure-like sensation in mid-chest, lasting 5-10 minutes, not clearly related to exertion. No associated dyspnea, diaphoresis, or nausea. Occurs 2-3 times per week. No nocturnal symptoms. Denies orthopnea.

CARDIAC RISK FACTORS: Hypertension, hyperlipidemia, positive family history, male gender, age >55.

PHYSICAL EXAM:
Cardiovascular: Regular rate and rhythm, no murmurs, rubs, or gallops. PMI non-displaced.
Lungs: Clear to auscultation bilaterally.

EKG: Normal sinus rhythm, no acute ST-T changes, no Q waves.

TROPONIN: <0.01 ng/mL (negative)

ASSESSMENT:
1. Atypical chest pain, rule out coronary artery disease (R07.9)
2. Essential hypertension (I10)
3. Hyperlipidemia (E78.5)

PLAN:
1. Exercise stress test scheduled
2. Continue aspirin 81mg daily
3. Continue atorvastatin 40mg daily
4. Continue lisinopril 20mg daily
5. If stress test positive, proceed to coronary angiography
6. Follow-up after stress test results
7. Lifestyle modification counseling""",

    "case_019": """EMERGENCY DEPARTMENT NOTE

Patient: Jennifer Martinez
DOB: 04/18/1990
Date: 03/18/2026 02:15 AM

CHIEF COMPLAINT: Chest pain

HISTORY OF PRESENT ILLNESS:
36-year-old female presents with sudden onset of sharp right-sided chest pain beginning 4 hours ago. Pain worse with deep inspiration. No radiation. Associated with mild dyspnea. Denies trauma. No leg swelling or pain. Recent 10-hour flight from Europe 2 days ago. No cough or fever. Patient reports being on oral contraceptives.

RISK FACTORS: Prolonged air travel, oral contraceptive use.

VITAL SIGNS: Temp 98.4°F, BP 118/74, HR 102, RR 22, O2 sat 94% on room air

PHYSICAL EXAM:
General: Alert, mildly anxious, in no acute distress
Cardiovascular: Tachycardic, regular rhythm, no murmurs
Respiratory: Decreased breath sounds right lower lobe, no wheezing
Lower extremities: No edema, negative Homan's sign

DIAGNOSTICS:
D-dimer: 2.4 mcg/mL (elevated)
CTA Chest: Pulmonary embolism right lower lobe segmental artery

EKG: Sinus tachycardia, no acute ST changes

ASSESSMENT:
1. Acute pulmonary embolism (I26.99)
2. Pleuritic chest pain secondary to PE (R07.1)

PLAN:
1. Admission to telemetry floor
2. Start therapeutic anticoagulation with apixaban
3. Discontinue oral contraceptives immediately
4. Lower extremity venous duplex to evaluate for DVT
5. Hematology consultation for hypercoagulability workup
6. Alternative contraception counseling
7. Patient stable for floor admission""",
}

IMAGE_CASE_METADATA = [
    {
        "case_id": "case_015",
        "expected_entities": [
            {"text": "lumbar disc herniation", "entity_type": "diagnosis", "start_char": 450, "end_char": 472, "negated": False, "qualifiers": ["L4-L5"]},
            {"text": "radiculopathy", "entity_type": "diagnosis", "start_char": 150, "end_char": 163, "negated": False, "qualifiers": ["right"]},
            {"text": "chronic low back pain", "entity_type": "diagnosis", "start_char": 530, "end_char": 551, "negated": False, "qualifiers": ["chronic"]}
        ],
        "expected_icd10_codes": ["M51.16", "M54.5", "M54.30"],
        "expected_principal_dx": "M51.16",
        "expected_comorbidities": ["M54.5", "M54.30"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "Denies bowel or bladder incontinence", "entity": "incontinence", "negated": True},
            {"text": "No history of trauma", "entity": "trauma", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "M51.16", "missing_qualifier": "with or without myelopathy", "query_hint": "Is myelopathy present?"}
        ],
        "kg_qualification_rules": [
            {"code": "M51.16", "requires": ["level", "with_without_myelopathy", "laterality"]},
            {"code": "M54.30", "requires": ["laterality"]}
        ]
    },
    {
        "case_id": "case_016",
        "expected_entities": [
            {"text": "diabetic foot ulcer", "entity_type": "diagnosis", "start_char": 50, "end_char": 69, "negated": False, "qualifiers": ["right foot", "plantar"]},
            {"text": "type 2 diabetes mellitus", "entity_type": "diagnosis", "start_char": 90, "end_char": 114, "negated": False, "qualifiers": ["type 2"]},
            {"text": "peripheral neuropathy", "entity_type": "diagnosis", "start_char": 135, "end_char": 156, "negated": False, "qualifiers": ["diabetic"]},
            {"text": "peripheral vascular disease", "entity_type": "diagnosis", "start_char": 162, "end_char": 189, "negated": False, "qualifiers": []}
        ],
        "expected_icd10_codes": ["E11.621", "E11.51", "E11.40", "I73.9"],
        "expected_principal_dx": "E11.621",
        "expected_comorbidities": ["E11.51", "E11.40", "I73.9"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "Denies fever or chills", "entity": "fever", "negated": True},
            {"text": "No purulent drainage noted today", "entity": "purulent drainage", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "E11.621", "missing_qualifier": "severity and depth of ulcer", "query_hint": "What is the Wagner grade of the ulcer?"}
        ],
        "kg_qualification_rules": [
            {"code": "E11.621", "requires": ["laterality", "depth", "location"]},
            {"code": "E11.51", "requires": ["specific_type"]},
            {"code": "I73.9", "requires": ["specific_diagnosis"]}
        ]
    },
    {
        "case_id": "case_017",
        "expected_entities": [
            {"text": "COPD", "entity_type": "diagnosis", "start_char": 180, "end_char": 184, "negated": False, "qualifiers": ["chronic"]},
            {"text": "exacerbation", "entity_type": "diagnosis", "start_char": 850, "end_char": 862, "negated": False, "qualifiers": ["acute"]},
            {"text": "dyspnea", "entity_type": "diagnosis", "start_char": 230, "end_char": 237, "negated": False, "qualifiers": ["progressive"]},
            {"text": "hemoptysis", "entity_type": "diagnosis", "start_char": 330, "end_char": 340, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["J44.1", "Z99.81", "Z87.891"],
        "expected_principal_dx": "J44.1",
        "expected_comorbidities": ["Z99.81", "Z87.891"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "Denies hemoptysis", "entity": "hemoptysis", "negated": True},
            {"text": "No fever documented", "entity": "fever", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "J44.1", "missing_qualifier": "with lower respiratory infection", "query_hint": "Is there documented lower respiratory infection?"}
        ],
        "kg_qualification_rules": [
            {"code": "J44.1", "requires": ["acute_chronic", "with_infection"]},
            {"code": "Z99.81", "requires": ["duration"]}
        ]
    },
    {
        "case_id": "case_018",
        "expected_entities": [
            {"text": "chest pain", "entity_type": "diagnosis", "start_char": 30, "end_char": 40, "negated": False, "qualifiers": ["atypical"]},
            {"text": "hypertension", "entity_type": "diagnosis", "start_char": 90, "end_char": 102, "negated": False, "qualifiers": ["essential"]},
            {"text": "hyperlipidemia", "entity_type": "diagnosis", "start_char": 104, "end_char": 118, "negated": False, "qualifiers": []},
            {"text": "orthopnea", "entity_type": "diagnosis", "start_char": 450, "end_char": 459, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["R07.9", "I10", "E78.5"],
        "expected_principal_dx": "R07.9",
        "expected_comorbidities": ["I10", "E78.5"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "Denies orthopnea", "entity": "orthopnea", "negated": True},
            {"text": "stress test negative for ischemia", "entity": "ischemia", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "R07.9", "missing_qualifier": "rule out CAD results", "query_hint": "What were the stress test results?"}
        ],
        "kg_qualification_rules": [
            {"code": "R07.9", "requires": ["location", "quality"]},
            {"code": "E78.5", "requires": ["specific_type"]}
        ]
    },
    {
        "case_id": "case_019",
        "expected_entities": [
            {"text": "pulmonary embolism", "entity_type": "diagnosis", "start_char": 680, "end_char": 698, "negated": False, "qualifiers": ["acute", "right lower lobe"]},
            {"text": "chest pain", "entity_type": "diagnosis", "start_char": 20, "end_char": 30, "negated": False, "qualifiers": ["pleuritic", "sharp"]},
            {"text": "trauma", "entity_type": "diagnosis", "start_char": 280, "end_char": 286, "negated": True, "qualifiers": []}
        ],
        "expected_icd10_codes": ["I26.99", "R07.1"],
        "expected_principal_dx": "I26.99",
        "expected_comorbidities": ["R07.1"],
        "expected_complications": [],
        "negation_test_cases": [
            {"text": "Denies trauma", "entity": "trauma", "negated": True},
            {"text": "No cough or fever", "entity": "cough", "negated": True}
        ],
        "cdi_gap_annotations": [
            {"code": "I26.99", "missing_qualifier": "acute vs chronic", "query_hint": "Is this acute or chronic PE?"}
        ],
        "kg_qualification_rules": [
            {"code": "I26.99", "requires": ["acute_chronic", "with_without_acute_cor_pulmonale"]},
            {"code": "R07.1", "requires": ["location"]}
        ]
    },
]


def generate_gold_standard():
    """Generate all gold standard test cases and files."""
    output_dir = Path("cliniq/data/gold_standard")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Create subdirectories
    (output_dir / "fhir_bundles").mkdir(exist_ok=True)
    (output_dir / "text_notes").mkdir(exist_ok=True)
    (output_dir / "images").mkdir(exist_ok=True)

    all_cases = []

    # Generate FHIR bundle files and add cases
    print("Generating FHIR bundle cases...")
    for case in GOLD_STANDARD_CASES:
        if "fhir_bundle" in case:
            fhir_path = Path(case["input_data"])
            fhir_path.parent.mkdir(parents=True, exist_ok=True)
            with open(fhir_path, "w") as f:
                json.dump(case["fhir_bundle"], f, indent=2)
            print(f"  - Created {case['case_id']}: {fhir_path}")

            # Add to master list (remove fhir_bundle field for gold standard JSON)
            case_copy = {k: v for k, v in case.items() if k != "fhir_bundle"}
            all_cases.append(case_copy)

    # Generate text note files and add cases
    print("\nGenerating text note cases...")
    for meta in TEXT_CASE_METADATA:
        case_id = meta["case_id"]
        text_path = Path(f"cliniq/data/gold_standard/text_notes/{case_id}.txt")
        text_path.parent.mkdir(parents=True, exist_ok=True)

        with open(text_path, "w") as f:
            f.write(TEXT_NOTES[case_id])
        print(f"  - Created {case_id}: {text_path}")

        # Add to master list
        case = {
            **meta,
            "source_type": "text",
            "input_data": f"cliniq/data/gold_standard/text_notes/{case_id}.txt",
            "notes": f"Text note case from {case_id}"
        }
        all_cases.append(case)

    # Add image cases metadata (images generated by separate script)
    print("\nAdding image case metadata...")
    for meta in IMAGE_CASE_METADATA:
        case_id = meta["case_id"]
        case = {
            **meta,
            "source_type": "image",
            "input_data": f"cliniq/data/gold_standard/images/{case_id}.png",
            "notes": f"Image case from {case_id}"
        }
        all_cases.append(case)
        print(f"  - Added metadata for {case_id} (image will be generated by generate_test_images.py)")

    # Sort by case_id
    all_cases.sort(key=lambda x: x["case_id"])

    # Write master gold standard JSON
    gold_standard_path = output_dir / "gold_standard.json"
    with open(gold_standard_path, "w") as f:
        json.dump(all_cases, f, indent=2)

    print(f"\n+ Generated {len(all_cases)} gold standard cases")
    print(f"+ Master file: {gold_standard_path}")
    print(f"+ FHIR bundles: {len([c for c in all_cases if c['source_type'] == 'fhir'])} cases")
    print(f"+ Text notes: {len([c for c in all_cases if c['source_type'] == 'text'])} cases")
    print(f"+ Image cases: {len([c for c in all_cases if c['source_type'] == 'image'])} cases")

    return all_cases


if __name__ == "__main__":
    generate_gold_standard()
